services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
      - mysql
      - vite
  php:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  mysql:
    image: "mysql:9.1"
    env_file:
      - ./env/mysql.env
  composer:
    build:
      context: .
      dockerfile: docker/composer.Dockerfile
    volumes:
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    build:
      context: .
      dockerfile: docker/npm.Dockerfile
    volumes:
      - ./src:/var/www/html
    entrypoint: ["npm"]
  vite:
    build:
      context: .
      dockerfile: docker/npm.Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    entrypoint: ["npm", "run", "dev"]
